# Generated by Django 4.0.3 on 2023-04-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_vacancy_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(choices=[('almaty', 'Алматы'), ('shymkent', 'Шымкент'), ('aktobe', 'Актобе'), ('astana', 'Астана')], max_length=100),
        ),
    ]
